version: "3.8"

services:
  web:
    build: ./src
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./src/:/app/
    ports:
      - "8100-8102:8000"
    environment:
      - DATABASE_URL=postgresql://srivathsan:fastapi_app_mnist
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "1"  # Limit CPU utilization to 1 CPU
    scale: 3  # Spin up multiple instances based on the number of CPUs in your laptop

  db:
    image: postgres:13.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=srivathsan
      - POSTGRES_PASSWORD=srivathsan
      - POSTGRES_DB=srivathsan_dev
    ports:
      - "5432:5432"

  prometheus:
    image: prom/prometheus
    container_name: prometheus2
    ports:
      - 9090:9090
    volumes:
      - ./prometheus_data/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana
    container_name: grafana2
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  prometheus_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./prometheus_data
  grafana_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./grafana_data
  postgres_data:

networks:
  default: 
    name: srivathsan
